import java.util.List;
import net.rithms.riot.api.endpoints.match.dto.Match;
import com.myproject.MatchAverages;

rule insertmatchdata 
ruleflow-group 'teamstats'
no-loop
when
    $matches : List()
    $match : Match() from $matches
    $averages : MatchAverages()
then
 System.out.println("****** in rule !");
    $averages.setTotalMatches($matches.size());
    insert($match);
end

rule evaluatematch
ruleflow-group 'teamstats'
when
    $match : Match()
    $averages : MatchAverages()
then
 System.out.println("****** in rule !");
    $averages.setTotalBaronKills( $averages.getTotalBaronKills() + $match.getTeams().get(0).getBaronKills() );
    $averages.setTotalDragonKills( $averages.getTotalDragonKills() + $match.getTeams().get(0).getDragonKills() );
    if($match.getTeams().get(0).isFirstBlood()) {
        $averages.setTotalFirstBlood( $averages.getTotalFirstBlood() + 1 );
    }
    $averages.setTotalTowerKills( $averages.getTotalTowerKills() + $match.getTeams().get(0).getTowerKills() );
    
    if($match.getTeams().get(0).getWin().equals("Win")) {
        $averages.setTotalWins( $averages.getTotalWins() + 1 );
    }
end

rule calculateaverages
salience -100
ruleflow-group 'teamstats'
when
    $averages : MatchAverages()
then
    System.out.println("****** in calc averages rule !");

    $averages.setAvgBaronKills((float) ((float)$averages.getTotalBaronKills() / (float)$averages.getTotalMatches()));
    $averages.setAvgDragonKills((float) ((float)$averages.getTotalDragonKills() / (float)$averages.getTotalMatches()));
    $averages.setAvgFirstBlood((float) ((float)$averages.getTotalFirstBlood() / (float)$averages.getTotalMatches()));
    $averages.setAvgTowerKills((float) ((float)$averages.getTotalTowerKills() / (float)$averages.getTotalMatches()));
    $averages.setAvgTotalWins((float) ((float)$averages.getTotalWins() / (float)$averages.getTotalMatches()));
end
